keys:
  - &macos-dev age1ek2kysw5xlw5gkrckpmty67g53v99rkm7lgrr8ds8dsm2l7fafmqzw5m54
  - &minecraft-server age1pf4qxy55qfp8ate5tkugr4f94dt8jygknyna455zea3ev8vmnalqfdaagn
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - age:
      - *macos-dev
      - *minecraft-server
