#!/bin/bash

# from https://github.com/edunfelt/base16-rose-pine-scheme
# ROSE Pine Moon
# can be generated by just putting 0xFF infront of all hex color values
#
export BASE01="0xFF2A273F"
export BASE02="0xFF393552"
export BASE03="0xFF6E6A86"
export BASE04="0xFF908CAA"
export BASE05="0xFFE0DEF4"
export BASE06="0xFFE0DEF4"
export BASE07="0xFF56526E"
export BASE08="0xFFEB6F92"
export BASE09="0xFFF6C177"
export BASE0A="0xFFEA9A97"
export BASE0B="0xFF3E8FB0"
export BASE0C="0xFF9CCFD8"
export BASE0D="0xFFC4A7E7"
export BASE0E="0xFFF6C177"
export BASE0F="0xFF56526E"
