name = "ServerPerformance"
author = "xM0Se"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33cb0e90a9f12dc73182f8c51a962ad5b513ad978feca461d5e3377859a543d0"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
