name = "ServerPerformance"
author = "xM0Se"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86a91cc0108179819f56ff907df201cf5f2353a25d7bff9749fcdbd30c96d34b"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
