name = "ServerPerformance"
author = "xM0Se"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "beaec3b54a6e4511ccfbb60bcd6333b4534d78b63d74d6c0fc9936200c9b8a62"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
