name = "Quality of Life Mods"
author = "xM0Se"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f86cc7f7cc64a3794342d74e3df17e9e85a77555202c689b03137d87648e0b40"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1"]
